tree-sitter/tree-sitter-php

grammar.js, src/grammar.json
Use `commaSep1` instead of declaring `class_interface_clause` recursively.
=> Simplify class_interface_clause

grammar.js, src/grammar.json
This fixes an issue where a `namespace_name_as_prefix` with a preceding slash within a `simple_parameter` would fail to parse:
```php
<?php
class Foo
{
public function bar(\Exception $exception)
{
}
}
```
I think the problem was that `prec.right` was committing too soon.
=> Add a conflict for namespace_name_as_prefix

index.js, package.json
Hi. 
First of all, thanks for a great tool!
As for the issue this PR fixes: `tree-sitter-php` doesn't export `nodeTypeInfo` as it uses root `index.js` as `main` in `package.json` instead of using `bindings/node` similar to what `tree-sitter-python` [does](https://github.com/tree-sitter/tree-sitter-python/blob/master/package.json).
Checklist:
=> Use bindings/node as main in package.json

grammar.js, script/parse-examples.js, src/grammar.json, src/node-types.json, src/scanner.cc, test/corpus/expressions.txt, test/corpus/literals.txt
After adding a few more test projects, a few more edge cases of the grammar was identified. This PR adds those test projects, fixes any surfaced errors and adds tree-sitter tests for them explicitly.
- Added test projects: Laravel Framework, MediaWiki
- Array destructuring changes:
- Added support for trailing comma
- Added support for skipping arguments
- Require at least one argument
- Added support for using Heredoc as function argument
Checklist:
=> Allows trailing comma and skipping arguments in array destructing and enables heredoc as function argument

grammar.js, src/grammar.json, src/node-types.json, test/corpus/expressions.txt
Fixes #92 by adding possibility of exponential op containing an unary op.
Also fixes precedence issue kindly pointed out by @Sjord 
Checklist:
=> Fixes #92: Error on exponentiation with expression

grammar.js, src/grammar.json, src/node-types.json, src/tree_sitter/parser.h, test/corpus/expressions.txt
After examining this case further, I've also added support for match expressions, and cast_expressions (only right-hand side)
Checklist:
=> Fixes #96:Parse error on exponentiation with augmented assignment

grammar.js, src/grammar.json, src/node-types.json, src/tree_sitter/parser.h, test/corpus/declarations.txt, test/corpus/expressions.txt
Adds support for references by combining two approaches:
1. Where anything included in `_callable_variable` is used directly, we wrap it in `by_ref`
2. Where there is a wrapping container already (or where `by_ref` simply doesn't make sense, like function returns) we apply the `reference_modifier` field
One new conflict has been added to disambiguate array creation and array destructing.
Also: Fixes float without decimal parts (but with trailing .)
Checklist:
=> Adds support for references

grammar.js, src/grammar.json, src/node-types.json, test/corpus/declarations.txt
Fixes parsing of attributes with anonymous class, closures, and arrow functions'. The problem was an incomplete attributes implementation.
Checklist:
=> Fixes Parse error for some attribute cases

grammar.js, src/grammar.json, src/node-types.json, test/corpus/string.txt
Avoid binary string rule breaking encapsed string when containing $b'
See #113 for problem details.
- Adding higher precedence to the content of $.string in order to avoid conflict with $.comment which is globally invoked by extras.
- Hack: Adding alias("'", $.string) to encapsed_string in order to avoid matching with the $.string rule (a more elegant solution would be very welcome)
Checklist:
=> Fixes #113 - avoid binary string rule breaking encapsed string

grammar.js, src/grammar.json, src/node-types.json, test/corpus/class.txt, test/corpus/declarations.txt, test/corpus/expressions.txt, test/corpus/types.txt
1. Replaces type_list with union_type everywhere except for in catch_clause to be more in line with the actual terminology in PHP
2. Reduces state count from 2519 to 2323 by reducing the combinatorial explosion I've caused when implementing other rules
3. ~~Reduces execution time of full test suite from 4-5 minutes to 46 s - 1 min by only doing shallow checkouts of repositories~~ - **Scratch that, I just realized that the tests are failing silently. Improvement coming in later PR**
This is a backwards incompatible change compared with code that's been in master since April 19th, but is not yet part of any release
=> Replaces type_list with union_type everywhere except for in catch_clause

src/scanner.cc
Checklist: ✅ 
👋 hello!
The `auto` typing is problematic for older c++ toolchains. In my case, it fails to cross-compile from x86_64-linux to aarch64-linux because of an old compiler. Declaring the type explicitly works fine though. What do you think?
=> use explicit typing for lexer lookahead

grammar.js, src/grammar.json, src/node-types.json, test/corpus/declarations.txt
Also fixes a bug with missing support for trailing comma in attribute listings
This changes the node structure for currently unreleased code.
Code:
```
#[
A1,
A2(),
A3(0),
A4(x: 1),
]
function a() {
}
```
Before:
```
(function_definition
attributes: (attribute_list
(attribute (name))
(attribute
(name)
parameters: (arguments)
)
(attribute
(name)
parameters: (arguments (argument (integer)))
)
(attribute
(name)
parameters: (arguments (argument name: (name) (integer)))
)
)
name: (name)
parameters: (formal_parameters)
body: (compound_statement)
)
```
After:
```
(function_definition
attributes: (attribute_list
(attribute_group
(attribute (name))
(attribute
(name)
parameters: (arguments)
)
(attribute
(name)
parameters: (arguments (argument (integer)))
)
(attribute
(name)
parameters: (arguments …
```
=> Adds attribute_group node to complete attributes support

grammar.js, src/grammar.json, src/node-types.json, test/corpus/class.txt
E.g.
```
class A {
public readonly string $prop;
}
```
Checklist:
=> Parse readonly properties

grammar.js, src/grammar.json, src/node-types.json, test/corpus/bugs.txt
=> Fixes bug #131 - Parse error when using self as constant

grammar.js, src/grammar.json, src/node-types.json, test/corpus/types.txt
This adds a new bottom_type only applicable to return types to represent the new "never" type.
Checklist:
=> Adds support for the never return type from the no_return RFC

grammar.js, src/grammar.json, test/corpus/bugs.txt
=> Fixes #133 - Incorrect precedence for error supression operator

grammar.js, src/grammar.json, src/node-types.json, src/tree_sitter/parser.h, test/corpus/class.txt
Adds support for constructor property promotion with readonly modifiers:
```php
// test/corpus/class.txt
<?php
class Point {
public function __construct(
public $x,
protected readonly $y,
private readonly int $z,
) {}
}
```
Checklist:
=> Adds support for constructor property promotion with readonly modifiers

grammar.js, src/grammar.json, src/node-types.json, test/corpus/types.txt
=> Adds support for intersection types

grammar.js, src/grammar.json, src/node-types.json, src/scanner.cc, test/corpus/execution_operator.txt, test/corpus/literals.txt
=> Adds support for interpolation in execution operators. Closes #135

queries/highlights.scm, test/highlight/literals.php
There's still a lot of work required to make the highlight queries very good
Checklist:
=> Fixes #148 by updating some highlight definitions around function and string

queries/highlights.scm, test/highlight/literals.php
=> Fixes #147: __DIR__ ignored by highlighting

grammar.js, src/grammar.json, src/node-types.json, test/corpus/class.txt
=> Add support for readonly class_declaration

grammar.js, src/grammar.json, src/node-types.json, test/corpus/expressions.txt
=> Fix empty match block parsing

Cargo.toml, grammar.js, package.json, src/grammar.json, src/node-types.json, src/tree_sitter/parser.h, test/corpus/types.txt
This commit introduce the new php8.2 `true` primitive type; It also adds tests to validate that `null` and `false` are treated as standalone type as described in this RFC: https://wiki.php.net/rfc/null-false-standalone-types
Ref: #139
See: https://wiki.php.net/rfc/true-type, https://wiki.php.net/rfc/null-false-standalone-types
Checklist:
=> Add support for `true` as a primitive type

grammar.js, src/grammar.json, src/node-types.json, test/corpus/declarations.txt
As documented [here](https://www.php.net/manual/en/language.enumerations.backed.php) the scalar equivalent of backed enums can only be `string` or `int`.
Checklist:
=> Only allow int and string as backed enum type

queries/tags.scm
This patch upstreams a few match queries used to extract symbols from `tree-sitter-php` parse trees used within GitHub.  All existing tag queries are untouched.
Checklist:
=> Add additional match queries

grammar.js, src/grammar.json
Dangling invalid references will be prohibited in Tree-sitter soon, this PR removes them because this repo is a tree-sitter dependency for corpus tests and it breaks tests in the tree-sitter main repo.
_Tree-sitter error reports:_
```
[stdin]:350
if (symbol.constructor == ReferenceError) throw symbol;
^
ReferenceError: Undefined rule: '_intrinsic'
at Object.get ([stdin]:209:23)
at Proxy.inline (.../tree-sitter/test/fixtures/grammars/php/grammar.js:90:7)
at grammar ([stdin]:343:40)
at Object.<anonymous> (.../tree-sitter/test/fixtures/grammars/php/grammar.js:32:18)
at Module._compile (node:internal/modules/cjs/loader:1254:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
at Module.load (node:internal/modules/cjs/loader:1117:32)
at Module._load …
```
=> Remove invalid `$._intrinsic` reference

src/scanner.cc
Hello!
Please see https://github.com/nvim-treesitter/nvim-treesitter/issues/4333 for reference, the `heredoc_end` rule includes whitespace---this PR removes that whitespace so the `heredoc_end` is just the identifier.
Checklist:
=> Remove extra whitespace from `heredoc_end`

grammar.js, src/grammar.json, src/node-types.json, test/corpus/class.txt
`final readonly` and `abstract class` are allowed in php but the tree-sitter parser throw an error.
Checklist:
=> fix parse error with `final` or `abstract` `readonly` classes

grammar.js, src/grammar.json, src/node-types.json, test/corpus/declarations.txt
This commit will correctly parse attributes on promoted properties.
This syntax is allowed and not recognize by this parser :
```php
<?php
class B {
public function __construct(
#[A]
public string $a,
) {
}
}
```
Checklist:
=> feat: allows attributes on promoted properties

Cargo.toml
This package cannot be published to crates.io without it.
Checklist:
=> chore: Add license to Cargo.toml

.github/workflows/ci.yml, package.json
Fixes `ModuleNotFoundError: No module named 'distutils'` in macos github action run.
=> Use python 3.12 and update node-gyp to 10.0.1

common/define-grammar.js, common/test/corpus/declarations.txt, php/src/grammar.json, php/src/node-types.json, php_only/src/grammar.json, php_only/src/node-types.json
Fixes #195 (note this was branched off of #192).
Apparently using heredocs/nowdocs in an enum is valid PHP:
```php
enum Suit: string
{
case Hearts = 'H';
case Diamonds;
case Clubs = "C";
case Spades = <<<TXT
S
TXT;
}
```
=> feat: allow enums to use double quoted strings and here/nowdocs

common/scanner.h, common/test/corpus/string.txt, php/src/tree_sitter/parser.h, php_only/src/tree_sitter/parser.h
Hello! This PR closes #209 and allows digits in heredoc identifiers, which is valid PHP.
Thanks!
=> fix: allow digits in heredoc identifier

common/define-grammar.js, common/test/corpus/types.txt, php/src/grammar.json, php/src/node-types.json, php/src/tree_sitter/parser.h, php_only/src/grammar.json, php_only/src/node-types.json, php_only/src/tree_sitter/parser.h
Hello!
This adds support for DNF types and subsequently closes #139 (note that this is branched from #192).
Thanks!
=> feat: support disjunctive normal form types

common/define-grammar.js, common/test/corpus/class.txt, php/src/grammar.json, php/src/node-types.json, php_only/src/grammar.json, php_only/src/node-types.json
Adds support for typed class constants: #197 (branched from #192)
Thanks!
=> feat: support typed class constants

common/define-grammar.js, common/test/corpus/class.txt, php/src/grammar.json, php_only/src/grammar.json
Hello!
This closes #154 (note this was branched from #192). 
A parser error was being generated when using the `final` modifier with a constant that also had a visibility. This was because the constant rule was conflicting with the `property_declaration` and `method_declaration` rules. Solution was to simply increase the precedence of the class constant declaration.
Thanks!
=> fix: final modifier with constant visibility

common/define-grammar.js, common/scanner.h, common/test/corpus/expressions.txt, php/src/grammar.json, php_only/src/grammar.json
See https://github.com/tree-sitter/tree-sitter-php/issues/142#issuecomment-1912776439 for more context: essentially the true definition of a legal identifier is consistent with what is currently listed on the docs: `^[a-zA-Z_\x80-\xff][a-zA-Z0-9_\x80-\xff]*$`
However, from my (limited) understanding there is a bug of sorts when PHP is parsing multibyte characters and instead compares the individual bytes which in practice allows characters outside the given regex to be parsed as identifiers.
This PR updates the grammar and scanner to allow the full utf-8 range as valid identifiers (`\u0080`-`\uffff`). PHP may even parse characters higher than this range (I haven't tested it), but given that utf-8 is already technically illegal I don't see …
=> feat: allow identifiers to contain utf-8 characters

common/define-grammar.js, common/test/corpus/bugs.txt, common/test/corpus/statements.txt, php/src/grammar.json, php/src/node-types.json, php_only/src/grammar.json, php_only/src/node-types.json
@amaanq, @cfroystad 
I'm not particularly fond of this solution, but I couldn't find a more elegant way to solve the problem...do you have any ideas?
The problem stems from the fact that the argument name is optional (if you make the argument name required then this issue goes away), a parse error is generated when an argument name clashes with any expression that starts with a keyword. I suspect that this is due to the keyword extraction, but I've tried adjusting the precedence to no avail.
Closes #161
=> fix: keywords not being parsed as named arguments

common/define-grammar.js, common/test/corpus/bugs.txt, common/test/corpus/string.txt, php/src/grammar.json, php_only/src/grammar.json
=> fix: error when string  contains php closing tag

common/define-grammar.js, common/test/corpus/bugs.txt, common/test/corpus/string.txt, common/test/highlight/literals.php, php/src/grammar.json, php_only/src/grammar.json
=> fix: comment precedence (again)

common/define-grammar.js, common/test/corpus/expressions.txt, common/test/corpus/statements.txt, common/test/corpus/types.txt, common/test/highlight/keywords.php, common/test/highlight/literals.php, common/test/highlight/types.php, common/test/highlight/variables.php, php/src/grammar.json, php/src/node-types.json, php_only/src/grammar.json, php_only/src/node-types.json, queries/highlights.scm
- `static` was removed from `primitive_types`
Changes:
- add `exit_statement`
- fix highlighting of `self` and `static`
- fix highlighting of `yield from`
- fix highlighting of `enum`
Closes #228
=> feat: add exit_statement and fix highlights

common/define-grammar.js, php/src/grammar.json, php_only/src/grammar.json
Hello!
This removes an incorrect choice from the `use_instead_of_clause`. The `insteadof` operator is meant to resolve conflicts between two traits with the same function name and therefore the desired trait must always be specified:
https://www.php.net/manual/en/language.oop5.traits.php#language.oop5.traits.conflict
Thanks!
=> fix: remove choice from `use_instead_of_clause`

common/define-grammar.js, common/test/corpus/expressions.txt, common/test/highlight/keywords.php, php/src/grammar.json, php/src/node-types.json, php_only/src/grammar.json, php_only/src/node-types.json, queries/highlights.scm
Updates the grammar to use the `$.static_modifier` instead of duplicating  `keyword("static")`
=> fix: use $.static_modifier instead of raw string

common/define-grammar.js, php/src/grammar.json, php/src/node-types.json, php_only/src/grammar.json, php_only/src/node-types.json, test/corpus/bugs.txt, test/corpus/class.txt, test/corpus/declarations.txt
Closes #251
I wasn't sure if attributes on interfaces is supported by PHP given that the [docs](https://www.php.net/manual/en/language.attributes.overview.php) state:
> Classes, methods, functions, parameters, properties and class constants can be the target of an attribute.
However, the PHP parser does parse them:
https://github.com/php/php-src/blob/a7bd911ad6a6045a9619eb56814569bff1b8bd03/Zend/zend_language_parser.y#L384-L390
Other changes:
- added attributes to trait declarations
- fixed error when `throw` is used as a named argument
- fixed error when passing variable by reference to promoted property
=> feat: add attributes to interfaces and traits

Package.swift
The Swift bindings were not updated correctly and fail to resolve this package when using Swift 6.
=> Fix Swift Bindings
